# config/settings.yaml

random_seed: 42

scenarios:
  - name: "2-Deck H17, Hi-Lo, 1-12 Spread"
    decks: 2
    dealer_hits_soft_17: true
    blackjack_payout: 1.5
    surrender_allowed: true
    double_after_split_allowed: true
    insurance_count_threshold: 3
    strategy: 
      counting: "zen count"         # Find list in README.md
      deviation: "deviations"   # Set to "basic" to use basic strategy only, edit strategy.yaml to change deviations
      spread: "basic"           # Set to false for no spread, edit spread.yaml to change spread
    penetration: 0.25
    base_bet: 15
    num_hands: 1000000

  - name: "8-Deck S17, Basic Strategy only"
    decks: 8
    dealer_hits_soft_17: false
    blackjack_payout: 1.5
    surrender_allowed: true
    strategy: 
      type: "basic"
      bet_spread: [1, 1]
    penetration: 0.8
    num_hands: 1000000