# config/strategy.yaml

basic:
  counts:
    - # all
      - #[0] => Regular
        [
          ["H","H","H","H","H","H","H","H","H","H"],          # 4-8
          ["H","DH","DH","DH","DH","H","H","H","H","H"],      # 9
          ["DH","DH","DH","DH","DH","DH","DH","DH","H","H"],  # 10
          ["DH","DH","DH","DH","DH","DH","DH","DH","DH","H"], # 11
          ["H","H","S","S","S","H","H","H","H","H"],          # 12
          ["S","S","S","S","S","H","H","H","H","H"],          # 13
          ["S","S","S","S","S","H","H","H","H","H"],          # 14
          ["S","S","S","S","S","H","H","H","RH","H"],         # 15
          ["S","S","S","S","S","H","H","RH","RH","RH"],       # 16
          ["S","S","S","S","S","S","S","S","S","S"],          # 17+
        ]
      - #[1] => Soft
        [
          ["H","H","H","DH","DH","H","H","H","H","H"],        # 13
          ["H","H","H","DH","DH","H","H","H","H","H"],        # 14
          ["H","H","DH","DH","DH","H","H","H","H","H"],       # 15
          ["H","H","DH","DH","DH","H","H","H","H","H"],       # 16
          ["H","DH","DH","DH","DH","H","H","H","H","H"],      # 17
          ["S","DS","DS","DS","DS","S","S","H","H","H"],      # 18
          ["S","S","S","S","S","S","S","S","S","S"],      # 19+
        ]
      - #[2] => Pair
        [
          ["PH","PH","P","P","P","P","H","H","H","H"],          # 2-2
          ["PH","PH","P","P","P","P","H","H","H","H"],          # 3-3
          ["H","H","H","PH","PH","H","H","H","H","H"],          # 4-4
          ["DH","DH","DH","DH","DH","DH","DH","DH","H","H"],          # 5-5
          ["PH","P","P","P","P","H","H","H","H","H"],          # 6-6
          ["P","P","P","P","P","P","H","H","H","H"],          # 7-7
          ["P","P","P","P","P","P","P","P","P","P"],          # 8-8
          ["P","P","P","P","P","S","P","P","S","S"],          # 9-9
          ["S","S","S","S","S","S","S","S","S","S"],          # 10-10
          ["P","P","P","P","P","P","P","P","P","P"],          # A-A
        ]

hi_lo:
  counts:
    - # count = -1
      - #[0] => Regular
        [

        ]